server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  shutdown: graceful
spring:
  devtools:
    add-properties: true
    livereload:
      enabled: true
  application:
    name: tutorials-management
  lifecycle:
    timeout-per-shutdown-phase: 20s
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      load-on-startup: 1
    log-request-details: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:tutorial-management
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 10000
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 10
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          generate_statistics: true
        format_sql: true
  web:
    resources:
      add-mappings: false
info:
  app:
    name: tutorials-management
    version: 0.0.1
    encoding: "UTF-8"
    java:
      version: 11.0.9